<script setup lang="ts">
import { onMounted, ref } from "vue"
import { api } from "../../../api/http"
import { useAction } from "../../../composables/useAction"
import JsonResult from "../../../components/JsonResult.vue"
const { output, error, busy, run } = useAction()
const projects = ref<Array<{ id: number; name: string }>>([]), projectId = ref<number | null>(null), batchId = ref<number | null>(null)
const itemId = ref<number | null>(null), revisionId = ref<number | null>(null), runId = ref<number | null>(null), resultId = ref<number | null>(null)
const caseIds = ref(""), environmentId = ref<number | null>(null)
const key = ref(crypto.randomUUID()), digest = ref(""), requestId = ref(""), attemptId = ref<number | null>(null)
async function action(target: number | null, action: string) { if (!target) return; return api("/internal/legacy/automation/actions", "POST", { target_id: target, action, digest: digest.value }, { "Idempotency-Key": key.value + ":" + action }) }
async function load() { projects.value = await api<Array<{ id: number; name: string }>>("/internal/legacy/projects"); return api('/internal/legacy/status') }
function newRequest() { key.value = crypto.randomUUID() }
onMounted(() => run(load))
</script>
<template>
  <section><h2>TestPilot 连接与用例对账</h2><div class="row"><button @click="run(load)">检查连接</button><label>项目 <select v-model="projectId"><option v-for="p in projects" :key="p.id" :value="p.id">{{ p.name }} · #{{ p.id }}</option></select></label><button :disabled="!projectId" @click="run(() => api(`/internal/legacy/projects/${projectId}/cases`))">读取用例</button><button :disabled="!projectId" @click="run(() => api(`/internal/legacy/projects/${projectId}/import`, 'POST'))">幂等同步用例</button><button :disabled="!projectId" @click="run(() => api(`/internal/legacy/projects/${projectId}/runs`))">运行记录</button></div></section>
  <section><h2>自动化批次、探索与脚本修订</h2><div class="row"><button @click="run(() => api('/internal/legacy/automation/batches'))">独立自动化批次</button><button :disabled="!projectId" @click="run(() => api(`/internal/legacy/automation/batches?project_id=${projectId}`))">项目批次</button><label>批次 ID <input v-model.number="batchId" type="number" min="1"></label><button :disabled="!batchId" @click="run(() => api(`/internal/legacy/automation/batches/${batchId}`))">批次详情</button><button :disabled="!batchId || busy" @click="run(() => action(batchId, 'start'))">请求探索</button></div><div class="row"><label>自动化项 ID <input v-model.number="itemId" type="number" min="1"></label><button :disabled="!itemId" @click="run(() => api(`/internal/legacy/automation/items/${itemId}/evidence`))">探索证据</button><button :disabled="!itemId" @click="run(() => api(`/internal/legacy/automation/items/${itemId}/revisions`))">脚本修订</button><button :disabled="!itemId || busy" @click="run(() => action(itemId, 'generate'))">请求生成脚本</button><button :disabled="!itemId || busy" @click="run(() => action(itemId, 'reexplore'))">补充探索证据</button></div><div class="row"><label>修订 ID <input v-model.number="revisionId" type="number" min="1"></label><button :disabled="!revisionId" @click="run(() => api(`/internal/legacy/automation/revisions/${revisionId}`))">修订与执行报告</button><button :disabled="!revisionId" @click="run(() => api(`/internal/legacy/automation/revisions/${revisionId}/import`, 'POST'))">登记来源摘要</button><button @click="run(() => api('/internal/legacy/automation/imported-scripts'))">登记资产</button><label>已核验脚本 SHA-256 <input v-model="digest"></label><button :disabled="!revisionId || !digest || busy" @click="run(() => api(`/internal/legacy/automation/revisions/${revisionId}/approve`, 'POST', { digest }))">批准该摘要</button><button :disabled="!revisionId || !digest || busy" @click="run(() => action(revisionId, 'run'))">执行获批脚本</button><button :disabled="!revisionId || !digest || busy" @click="run(() => action(revisionId, 'retry'))">重试获批脚本</button><label>执行尝试 ID <input v-model.number="attemptId" type="number" min="1"></label><a v-if="attemptId" :href="`/internal/legacy/automation/attempts/${attemptId}/report/index.html`" target="_blank" rel="noopener">下载报告入口 HTML</a></div></section>
  <section><h2>受控请求与运行证据</h2><div class="row"><label>旧系统用例 ID（逗号分隔）<input v-model="caseIds"></label><label>测试环境 ID <input v-model.number="environmentId" type="number" min="1"></label><button :disabled="!projectId || !caseIds || busy" @click="run(() => api(`/internal/legacy/projects/${projectId}/runs`, 'POST', { case_ids: caseIds.split(',').map(Number), environment_id: environmentId }, { 'Idempotency-Key': key }))">请求测试运行</button><button @click="newRequest">新请求</button><label>本地请求 ID <input v-model="requestId"></label><button :disabled="!requestId || busy" @click="run(() => api(`/internal/legacy/requests/${requestId}/reconcile`, 'POST'))">核对目标实际状态</button></div><div class="row"><label>运行 ID <input v-model.number="runId" type="number" min="1"></label><button :disabled="!runId" @click="run(() => api(`/internal/legacy/runs/${runId}/results`))">逐用例结果</button><button :disabled="!runId" @click="run(() => api(`/internal/legacy/runs/${runId}/import`, 'POST', { product_build: 'not_verified', role: 'test', environment: environmentId }))">登记运行证据</button><button @click="run(() => api('/internal/legacy/imported-runs'))">本地对账记录</button></div><div class="row"><label>结果 ID <input v-model.number="resultId" type="number" min="1"></label><a v-if="resultId" :href="`/internal/legacy/results/${resultId}/trace`">下载轨迹</a><a v-if="resultId" :href="`/internal/legacy/results/${resultId}/video`">查看录屏</a></div></section>
  <JsonResult :value="output" :error="error" :busy="busy" />
</template>
